### ISSUE TITLE
dealing with new derived input files

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#10]
Right now, looper is still checking for input file existing based on the (soon to be outdated) "data_source" and its derived "data_path" attributes. Now with derived columns, any column could be the input source.

Instead, I propose we switch the input file checks to check for all (populated) derived columns for files to exist.

Thoughts?

**Comment by nsheff** [comment]
See also my comment in 1e08758760b8a12e4240ac736df5132a8871d122 regarding bsf-specific checks.

**Comment by afrendeiro** [comment]
Could you please explain what are derived columns? From here (http://looper.readthedocs.io/en/latest/advanced.html) I still can't understand what they are.

**Comment by nsheff** [comment]
yeah those docs are just a placeholder. I tried to explain it earlier in the release note e-mail.

but it's simple: just variable columns set in the project config that act like the original "data_source" column. now you can have as many as you want.

it's very useful for, for example, samples with read1/read2 split fastq inputs, and in the future, for multi-sample comparison tables. it makes looper extremely flexible, you can run it on any entities now, not just samples.

**Comment by afrendeiro** [comment]
Okay. One or two examples of practical usage would be very useful though.

**Comment by nsheff** [comment]
I made a major update to try to explain this. What do you think?

http://looper.readthedocs.io/en/latest/advanced.html#pointing-to-flexible-data-with-derived-columns

**Comment by afrendeiro** [comment]
It's great!

Regarding your initial question (should we check the existence of files in all columns generated by derived columns?), I think this actually can be used to produce variables that aren't necessarily files right?
For example, I could have the root directory of a sample, or some file with stats specified in this way. Unlikely to be used, but a possibility.

**Comment by nsheff** [comment]
Yes, you're right. I've only used it for files so far. "some file with stats" is still a file, though, and so is "root directory for a sample" (if a directory qualifies as a file). Still files, if not input files. Can you think of anything that would *not exist*?

And the more I use looper, the more I realize it is more flexible than we originally realized, so I think we should keep it flexible if we can.

But this means you can't really systematically check for input files existing, right?

**Comment by afrendeiro** [comment]
The examples I gave are path to files, yes - but they might not yet exist at the time the sample is instantiated (i.e. produced during the pipeline run or in a later analysis), so checking them might not make much sense at that point.

> But this means you can't really systematically check for input files existing, right?

Yes, I guess this is the compromise. We probably need to make the user aware that only `data_source` is interpreted as the path to the input file and that is checked.

**Comment by nsheff** [comment]
But if these files are to be created later, should they really be in the annotation sheet list in the first place?

2nd idea: what about just eliminating the file checks altogether?

I would vote for either: all derived columns are checked; or, there are no checks. I see no reason to treat "data_source" differently.

**Comment by afrendeiro** [comment]
Well, they really *aren't* in the annotation sheet, they are built from variables that are there - for someone that could be advantageous.
Anyway if it is between those two choices you might as well check all files then.

**Comment by nsheff** [comment]
Yes, you're right.

What do you suggest? what about having a parallel section alongside `derived_columns` called `built_files` or something that aren't checked?

I guess the basic advantage of file checks is that jobs without all input files won't be submitted.

So there needs to be a way in the project sheet to specify which files are inputs and which are not

**Comment by afrendeiro** [comment]
Which of the variables holds a value for the input files is an independent issue from checking all derived columns for the existence of a file.

I propose we make this configurable (through the project config) but with a default `data_sources`, similar to the `results_subdir` and `submission_subdir`. This would assure both backward compatibility and improved configurability.

We can then check either only that for the existence of input files, or all - no big preference.

**Comment by nsheff** [comment]
Ok good. then I propose a new config attribute called `required_inputs`. 

by default this can have `data_source` as a required input (although I question if this should be a default), and the user can put any other columns in there.

this is a nice solution because it also doesn't require you to use derived columns at all, if you want to hard code paths for example.

next question then is what is the default for `required_inputs` ? `null` or `data_source`? I vote for `null` so any required inputs must be made explicit.

**Comment by nsheff** [comment]
Are there any other comments or suggestions relating to this proposal? ideas from @fhalbritter @jklughammer @cdietzgit ? Is the proposed solution acceptable?

**Comment by afrendeiro** [comment]
If we make the `required_inputs` an empty list by default (which I guess is what you propose with `null`), then we have to always specify it, which goes against our current "minimal sensible defaults" phylosopy to have a minimal config.
`data_source` though is *a* default like any other, but is already in use and I think we should stick to that.

**Comment by afrendeiro** [comment]
Also, I think right now, there is some confusion in `Sample.set_file_paths()` regarding this.

The first section calling `Sample.locate_data_source()` uses `data_source` as the keyword to expand paths as before, then the same for each derived column (which apparently the user would specify in the prj config). Then the section handling `required_inputs` only gathers the attributes of the sample which are in `required_inputs`, but this is not used anywhere else in the code. Very confusing.

How should we sort this out? I think we need to separate expanding paths from derived columns from which of these holds a path to the input files(s) somehow.

**Comment by nsheff** [comment]
No... if there is no `required_inputs`, then looper will not bail on anything... it won't have to be specified. Actually, this is better because it means you don't require any particular columns, making minimal requirements extended to the sample annotation.

You only have to specify required inputs if you want it to fail if something doesn't exist. Actually now that I think about it, this should be specified by the pipeline, not by the project, right? 

The code is confusing because I only ever partially implemented `required_inputs`, sorry. I was waiting for feedback above), which as you can see, never came.

So, here's a new concept: `required_inputs` is not in project config at all, but in `pipeline_interface`, specified by the pipeline author. Actually, this makes way more sense, because different data types may require different inputs, and it's the pipe that will determine; so projects with different data types will not be amenable to the direction we were going of a `required_inputs` attribute in project_config.

**Comment by nsheff** [comment]
So, `pipeline_interface` would have something like:

```yaml
rrbs.py:
  name: RRBS
  looper_args: True
  arguments:
    "--sample-name": sample_name
    "--genome": genome
    "--input": data_path
    "--single-or-paired": read_type
  required_inputs: [data_path]
```
`required_inputs` would be optional. Maybe it's better called `required_files`.

for pipelines that can take either 1 or 2 inputs (like rnaBitSeq), there's no good answer, because it depends on the same itself, whether it should require 1 or 2 inputs. I think there's no solution to that.

The automatic read-length checks would just go against anything in requried_inputs that is named *.bam or *.fastq or *.fastq.gz

But keep in mind, inputs could be anything... it might be a `.hic` file, for instance, for a secondary pipeline.

**Comment by nsheff** [comment]
See also: https://github.com/epigen/pipelines/issues/34

**Comment by nsheff** [comment]
@afrendeiro I think this is the last remaining pending thing that I think we should just solve before we merge... any thoughts?

**Comment by nsheff** [comment]
I have a working implementation of this now. check it out.

**Comment by afrendeiro** [comment]
Okay let's see if i understood:
Different pipelines might need different inputs (e.g. 1 file, 2+ files). In your implementation the pipelines state this and require the user to have to have (or build with derived columns) attribute(s) that are required by the pipelines and will be used as input file by them. Am I correct?

This is somewhat complicated. A few questions:
 - How will the user know what attribute(s) each pipeline needs to specify them in the annotation sheet? <- this seems critical to maintain simplicity, or else building a sample sheet will be a nightmare
 - Your implementation focuses on the `PipelineInterface` object to handle this. How will this interface with the sample objects? `sample.data_path` seems obsolete from now on:
    - what will happen to `sample.locate_data_source`? (and other sample functions that rely on its input files)
    - can we assign `sample.data_source` to a list of required_inputs (that would be specific for that sample type since these come from the pipelines) so that we can always get the input files of that sample without knowing specifically what files are required by the pipeline of that sample? (might be useful also for things like get input file sizes, etc...)
  - what happens if a pipeline wants to accept either 1 or more files for example?

**Comment by nsheff** [comment]
> Am I correct?
You are correct. Input files (can) vary by pipeline, so the pipeline must state this.

It feels complicated because we made all our pipelines standardized so they require exactly 1 input, and all exactly the same input. But most people won't do this (it restricts what the pipelines can do).

> How will the user know what attribute(s) each pipeline needs to specify

When a user wants to use a pipeline, the user *must* know what inputs that pipeline takes. There is no way around this... short of specifying "all pipelines must take exactly 1 input, in a column called `data_source`", there is no way around this complexity. But that solution is severely limiting for pipeline authors. My pipelines no longer do this; hence the need for this new thing. Essentially, each pipeline must say "You must define these columns". This doesn't seem to difficult... For our suite of pipelines, we can make it simple: "you must define a data_source column" if that's what we want. But now, others can say their pipelines require different inputs. What about a pipeline that compares HiC data to H3K27ac data? It needs 2 inputs with very different characteristics. This is not possible with the old fixed system.

> Your implementation focuses on the PipelineInterface object...sample.data_path seems obsolete from now on: 

PipelineInterface reads the pipeline_interface.yaml -- then all it needs is a sample object and it can determine if the sample has everything needed for any given pipeline. This is how I implemented it, it seems to make sense to me...Indeed -- sample.data_path is now obsolete (and I suggest removing it in favor of the more universal and generic derived columns) -- but sample.data_source could remain a default derived column to the safe effect from the user point of view. So this stuff is all still in there; (`locate_data_source` or something equivalent is still used, now more generically, for all columns listed in `derived_columns`, which defaults to `data_source`).

> can we assign sample.data_source to a list of required_inputs

This is just conceptually flawed because required_inputs is not a sample attribute, but a combined attribute relative to both a sample and a pipeline. In other words, we can't set required inputs for a sample unless we know what pipeline is being run. 1 sample can run 2 pipelines, and the required inputs differ; therefore, we shouldn't set that as a sample attribute. it's the wrong way to think about it. nevertheless, we can temporarily set it for convenience when working with a particular pipeline/sample pair... but we have to realize this is an instantiation of a sample *with a particular pipeline run* and not a generic sample.

> what happens if a pipeline wants to accept either 1 or more files for example?

for pipelines accepting 1 or more files; the 1 file is listed as required, and this is all that is checked for pipeline submission. The other files are listed in the interface under `all_input_files` so these can be tallied for total input size. This highlights another issue solved by this method: the input size calculation can now be tailored to any inputs, as specified by the pipeline author (defaults to anything listed as a required input).

Another thing this solves is thus: inputs are relative to a pipeline run, not to a sample. 1 sample may have 2 input files (like, a microarray experiment and a sequencing experiment). Different pipelines may require different of those inputs. You don't want the Project object to check these at instantiation; you only want it to check when it's about to submit a pipeline. In short, Projects should be decoupled from input files, to make them totally generic; samples can be anything; maybe don't even have inputs. Inputs only become required when we want to do some action (a pipeline) on an input, at which point, the inputs are evaluated because they vary based on the action.

I could explain this more simply in person, but in the end, I think this does not add any new complexity for the user, while greatly increasing flexibility for pipeline authors. It should seem straightforward that to run a given pipeline on a given sample, that sample must define all the inputs required for that pipeline, and that this can vary by pipeline. In addition, at submission, the pipeline can give an easy-to-follow reminder ("you submitted the `xyz` pipeline, which requires a column named `blahblah`, but this did not exist in your input file, so I am not submitting this pipeline") -- very easy for the user to figure out what to include for samples that need that pipeline.

also enables secondary pipelines that run on outputs from earlier pipelines more easily.

**Comment by afrendeiro** [comment]
(The reason why I prefer this type of media is that these discussions will be available to consult later and are searchable. Also at least in my case it also forces me to be much more concise and structured in the discourse.)

Okay I understand.

However, I'd like to comment on the development process of this - please take it as constructive criticism as that's my intention: When modifying/implementing a feature we should be aware of all its implications. I think it's good practice to avoid loose ends of code (pieces of code/functions no longer used after) and redundancy (by modifying code) instead of writing a parallel implementation.
This is obviously difficult but let's make an effort to keep the project tidy. Maybe something like this could be helpful: http://pycallgraph.slowchop.com/en/master/

**Comment by nsheff** [comment]
Yes, this is starting to get a bit out of hand here. I have started a new branch and it is taking me deeper than I anticipated -- but I did put it in a new branch, so it causes no problems to anyone as I work.

Also some of the loose ends are because it's in process... the concepts are still being worked out and that creates confusion. When things resolve, the code can become much cleaner if we take the time to re-structure based on the final state. I'm working on that now, but it can always be improved. I'm reluctant to take stuff out immediately in case it ends up useful shortly, but it should be removed eventually. but anyway, it's always in the git history.

But what specifically are you referring to, as far as parallel implementation? Specific suggestions welcome of course.

**Comment by nsheff** [comment]
If you could give this a try and see if you can get it to work and make sense, that would be helpful. Then I can go through and clean up the preliminary stuff that is no longer necessary. Here are some notes:

The idea is that a sample is first created with all of its universal attributes. Later, additional attributes that are relative to a particular pipeline will be added. This enables different pipelines to specify different requirements for the same sample. Previously this was not possible. It wasn't a problem, because all of our pipelines use the exact same input type: a single bam file. But for flexibility, we have to realize that other pipelines could conceivably use different types of input, including multiple different input types in a single pipeline. There is no reason looper can't also handle these types pipelines easily, and including the simple case.

So, I have now created three new configuration options that can be added to the pipeline interface config file. These are optional, and the system well try to default to something sensible if they are not provided. They are:

`required_input_files`: this is a list of file attributes that the pipeline requires. In the past, this was always just data path. Now, the pipeline author can define which attributes are required. If a sample does not have one of the attributes included in this list, the pipeline will not be submitted. This defaults to empty, meaning there is no required input file. This does not add any difficulty for a pipeline user, and just requires a single new definition for a pipeline author. Each pipeline specifies what it requires in the interface.  Our pipelines will add `required_input_files: [data_path]` to the interface and then work as before.

`all_input_files`: in the event that a pipeline has input files that are not required, yet should still be counted for the file size calculation that determines resource use, the pipeline author may add an optional pipeline interface configuration attribute to specify all input files. Looper will use these attributes to sum up the total input size for resource allocation. By default, this will simply be exactly the same as `required_input_files`. If neither is specified, it will be impossible for looper to know what attributes are input files, and therefore will not be able to request appropriate resources; so it's important for a pipeline author to define at least 1 of these two.

`ngs_inputs`: since some pipelines may require sequencing data, like ours, but other pipelines may require different types of input, we cannot assume that we can run read type or read length calculations on inputs generically. Instead the pipeline author must specify which attributes contain NGS files. Looper will use these files to assess read length and read type automatically. If no NGS input attributes are specified in the pipeline interface, looper will simply not automatically populate these attributes.

These are three fairly simple additions to the pipeline interface which are entirely optional, but provide excellent customizability for a pipeline author.

In practice what happens, is that looper will assess these interface-specific sample questions as it submits each pipeline, allowing this to be independent from the initial sample creation, such that each pipeline submission has its own evaluation of these attributes. This way, a sample that satisfies one pipeline but not another will still be able to submit the pipelines that it satisfies, and the others will simply not be submitted. This means that at project creation, it doesn't make sense to check sample for sample input, so this has been removed.

Finally, it had not previously been implemented that derived columns could populate columns in a merge table. This now works.

**Comment by afrendeiro** [comment]
Okay sounds very good. I've had a look at the code and also ran some microtest samples and it all went okay.

Just a question: if a pipeline does not specify `required_input_files` in the interface, the sample will not obviously be checked for those attributes, but it will still be submitted to that pipeline anyway, right?

What I meant before with parallel implementations was more "duplicate" implementations such as the new in the inputs branch and the previous `Sample.check_valid`, because I though both were still being used just in different parts of the code. I guess `Sample.check_valid` is obsolete now and `locate_data_source` should probably be renamed to something like `expand_derived_attributes/columns` since it is generic and not only for generating the path to the input data.

**Comment by nsheff** [comment]
Yes, there were some duplicates in there in my intermediate commits. I think I've cleaned all that up now.

> I guess Sample.check_valid is obsolete now
 `check_valid` is different, though... but it is a bit of relic, since we used to check more stuff. If you can simplify it away, great. right now it's still being used to check for `sample_name` -- different from file checks.

>Just a question: if a pipeline does not specify required_input_files in the interface, the sample will not obviously be checked for those attributes, but it will still be submitted to that pipeline anyway, right?

The sample will not be checked for any input files and will therefore be submitted. It will have to have all attributes used  in the "arguments" section -- that's independent of input file checks.

>locate_data_source should probably be renamed 
agreed.



Renaming

**Comment by nsheff** [comment]
Go ahead and make any changes you want and when you're done, I'll merge everything back into master and tag as 0.4-rc1 on Monday -- we can give some time for people to test that release candidate before finalizing it to 0.4, if everything works as expected.

**Comment by nsheff** [comment]
In version 0.4, required_inputs became relative to a pipeline submission; `data_path` became deprecated, and `data_source` because the default `derived_column`. This issue is solved.

**Comment by vmsiva** [comment]
I started working on the looper.Could you please share is there any video tutorials(Links) for Looper.

**Comment by nsheff** [comment]
@vmsiva There are no video tutorials. Your best bet is the documentation: http://looper.readthedocs.io/

PS we're getting ready to release version 0.6 next week so that might be a good time to start
