### ISSUE TITLE
Broken Sample.make_sample_dirs

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#100]
The [`make_sample_dirs`](https://github.com/epigen/looper/blob/master/looper/models.py#L1234) function from `Sample` is broken since the introduction of AttributeDict metadata ("_force_nulls", "_attribute_identity"). It fails because these attributes are boolean values and _os.path.exists fails with a TypeError if that gets passed.

**Comment by nsheff** [comment]
Indeed. let's override the `__dict__` method on AttributeDict to not provide metadata... thoughts?

**Comment by afrendeiro** [comment]
I don't mind additional metadata, but I was just surprised to have non-string values in the 'paths' AttributeDict when I expected all values in there tobe filled with strings after sample creation.
Alternatively, we can also just wrap a try statement around the os.path.exists call.

**Comment by nsheff** [comment]
But I think really just in general `__dict__` should return actual values, not information describing the object...

**Comment by nsheff** [comment]
we should have different functions for querying metadata.

**Comment by nsheff** [comment]
by the way, @afrendeiro are you by chance still using a `paths` section in your project config? If you stick those into `metadata` does that solve the problem?

**Comment by vreuter** [comment]
https://github.com/epigen/looper/pull/98 now addresses this and adds some regression test logic

**Comment by nsheff** [comment]
Ok @afrendeiro this should be solved now in the `dev` branch. reopen if you have further problems.
