### ISSUE TITLE
Custom exceptions should be private

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#120]
Right now exceptions are defined as classes, like this:
```
class InvalidResourceSpecificationException(Exception):
    """ Pipeline interface resources--if present--needs default. """
    def __init__(self, reason):
        super(InvalidResourceSpecificationException, self).__init__(reason)
```
These will clutter our automatic API here: http://looper.readthedocs.io/en/latest/api.html
Can we define them private (with `_` names) to exclude them from these public APIs?

**Comment by vreuter** [comment]
Yeah good idea

**Comment by vreuter** [comment]
https://github.com/epigen/looper/pull/122
