### ISSUE TITLE
looperenv environment variable error

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#124]
Looks like environment variable name 'LOOPERENV' changed? it's no longer being picked up, and suggests instead a variable called `COMPUTE_SETTINGS` which is incorrect:
```
Loading COMPUTE_SETTINGS: /home/ns5bc/.local/lib/python2.7/site-packages/looper/submit_templates/default_looperenv.yaml
Using default COMPUTE_SETTINGS. You may set environment variable COMPUTE_SETTINGS to configure environment settings.
```

**Comment by nsheff** [comment]
It does this on `looper check` but not on `looper run`. strange.

**Comment by vreuter** [comment]
My bad; I forgot to redefine that property on the `looper`-specific `Project`. https://github.com/epigen/looper/pull/125 should address this
