### ISSUE TITLE
lumping jobs together

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#126]
Here's a feature suggestion:

I have a project with lots (2,000) samples to run. Each sample only takes about 10 minutes to run. Rather than submitting 2k jobs that each take 10 minutes, I'd rather lump each 10 samples together and submit 200 jobs that take 100 minutes.

I propose a `--lump 10` command line argument to looper (also configurable in the project_config?) which would stick 10 jobs serially into a single submission script.

**Comment by nsheff** [comment]
this one is going to be very useful for the SRA conversions I'm working on now. RIght now get_geo is doing them serially, but I want to route them through looper. But since we probably don't need to submit an individual job for each, this could be useful here.

**Comment by vreuter** [comment]
This is looking pretty good, primarily handled in these two commits:
https://github.com/epigen/looper/commit/7f294c992c43b91e89115d93aba545099d8d1aa7
https://github.com/epigen/looper/commit/2f72e97bfcc213bdbf43bd0de41edf87e0489317

**Comment by nsheff** [comment]
Yeah, I can confirm that your latest branch is working as expected now.

**Comment by vreuter** [comment]
Cool, thanks! Also, just for record-keeping--code that was largely replaced by the first of those commits is now removed in:
https://github.com/epigen/looper/commit/03f4f0b989c109c18a56812424af829ddc91c2a9
