### ISSUE TITLE
Extending Sample from library-specific object not working

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#129]
Hi,

Are there tests cases on the current implementation of sample-type (library)-specific Sample objects that extend Sample [as described in the docs](http://looper.readthedocs.io/en/latest/models.html#extending-sample-objects)?

This works on 0.5 but is not on 0.6rc1 (only generic Sample objects are created).

**Comment by nsheff** [comment]
Well, probably not then... this should still work. 

When I tried I got a missing `pd` error -- did you try adding `import pandas as pd` ?

What's the exact error?

**Comment by vreuter** [comment]
Yeah definitely no cases for that, but that's something that should be added along with the resolution to this.

**Comment by vreuter** [comment]
This would happen silently if the import of `pipelines` fails. That may be happening? Regardless, we should add some messaging (quiet, at `DEBUG` or `INFO`) about what's going on with the import attempts.

**Comment by nsheff** [comment]
This brings up a bigger point, though -- wasn't there some discussion about the `__library__` attribute and didn't we think of a better way to do this long term using the pipeline interface?

**Comment by afrendeiro** [comment]
I'm all up for different/better ways of extending Sample objects but since the current code on that seems to be unchanged and the docs still point to the same behaviour as before I just assumed there wouldn't be changes there.

Currently there is no error thrown per design and only generic Sample objects are created if none of these happen: there is no "pipelines" package installed; there is no python file under the pipeline_dir specified in the config file with a __library__ attribute matching the "library" attribute of a sample. One of these is happening to me now.

**Comment by nsheff** [comment]
Ok I understand now. Yes, that makes sense and it should stay this way for now. sorry for the distraction.

yes, debug code would be helpful. there is a little bit (line 1110 in models.py) -- what does it say for you with if you turn on the debug code ( with `--dbg` ?). Vince how do you turn on debug code if you're using models interactively? I haven't done this before...

**Comment by vreuter** [comment]
Hm I've not had occasion to do it either, but my instinct would be to add a handler at `DEBUG` level to the root logger. Let me give it a shot and see if that works, though...

**Comment by vreuter** [comment]
Yeah that seems to work.
```
import logging
import sys
h = logging.StreamHandler(sys.stdout)
h.setLevel(logging.DEBUG)
logging.root.setLevel(logging.DEBUG)
logging.root.addHandler(h)
```

**Comment by vreuter** [comment]
I just pushed an RC2 branch with a bit more messaging in this section of the control flow, and updated the interactive test module to have this log setup (at `looper.tests.interactive`). If you try that out, let me know how it's working (any problems, additional helpful features).

**Comment by afrendeiro** [comment]
That logging for interactive use is amazingly useful - thank you!

[off topic: can we in the future have something like a `looper.logger()` function activate that? Maybe also a way to control verbosity e.g. `looper.set_logging_level("DEBUG")`?]

So here's my log until the part where it starts creating Sample objects.
It does not import an installed pipelines package (as it shouldn't) but it does find my pipelines_dir and manages to import a pipelines package from there.
I cannot see however if the issue is finding the classes from the pipelines package or pairing them with the sample's library (both of which work in 0.5).

```rst
Creating Project from file: 'metadata/project_config.yaml'
Establishing default environment settings
Loading PEPENV: /home/arendeiro/.local/lib/python2.7/site-packages/looper/submit_templates/default_compute_settings.yaml
Parsed environment settings: {'compute': {'default': {'submission_command': 'sh', 'partition': 'longq', 'submission_template': 'localhost_template.sub'}, 'slurm_cemm': {'submission_command': 'sbatch', 'partition': 'longq', 'submission_template': 'slurm_template.sub'}, 'econ': {'submission_command': 'sbatch', 'partition': 'economy', 'submission_template': 'slurm_template.sub'}, 'local': {'submission_command': 'sh', 'submission_template': 'localhost_template.sub'}}}
Updating key: 'compute'
Updating key: 'default'
'default' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'slurm_cemm'
'slurm_cemm' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'econ'
'econ' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'local'
'local' now has keys ['submission_command', 'submission_template']
'compute' now has keys ['default', 'econ', 'slurm_cemm', 'local']
Updating key: 'environment'
Updating key: 'compute'
Updating key: 'default'
'default' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'econ'
'econ' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'slurm_cemm'
'slurm_cemm' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'local'
'local' now has keys ['submission_command', 'submission_template']
'compute' now has keys ['default', 'econ', 'slurm_cemm', 'local']
'environment' now has keys ['compute']
Using default PEPENV. You may set environment variable PEPENV to configure environment settings.
Establishing project compute settings
Creating Project compute
Updating key: 'compute'
'compute' now has keys []
Adding entries for setting 'default'
Compute: {'submission_command': 'sh', 'partition': 'longq', '_attribute_identity': False, 'submission_template': '/home/arendeiro/.local/lib/python2.7/site-packages/looper/submit_templates/localhost_template.sub', '_force_nulls': False}
Parsing Project config file
Setting Project data from '/scratch/lab_bock/shared/projects/arid1a/metadata/project_config.yaml'
Adding attributes for Project: ['username', 'compute', 'data_sources', 'transcriptomes', 'genomes', 'pipeline_config', 'trackhubs', 'email', 'metadata']
Config metadata: {}
Updating key: 'compute'
'compute' now has keys ['submission_command', 'partition', 'submission_template']
Updating key: 'data_sources'
'data_sources' now has keys ['bsf', 'local']
Updating key: 'transcriptomes'
'transcriptomes' now has keys ['human']
Updating key: 'genomes'
'genomes' now has keys ['human']
Updating key: 'pipeline_config'
'pipeline_config' now has keys ['atacseq']
Updating key: 'trackhubs'
'trackhubs' now has keys ['url', 'trackhub_dir']
Updating key: 'metadata'
'metadata' now has keys ['submission_subdir', 'merge_table', 'sample_annotation', 'output_dir', 'pipelines_dir', 'results_subdir']
Project now has 14 keys: ['username', 'compute', 'permissive', 'transcriptomes', 'genomes', 'environment', 'pipeline_config', 'data_sources', 'environment_file', 'file_checks', 'trackhubs', 'config_file', 'email', 'metadata']
No subproject
Project metadata: {'submission_subdir': 'submission', '_force_nulls': False, 'merge_table': '/scratch/lab_bock/shared/projects/arid1a/metadata/merge_table.csv', 'sample_annotation': '/scratch/lab_bock/shared/projects/arid1a/metadata/annotation.csv', '_attribute_identity': False, 'output_dir': '/scratch/lab_bock/shared/projects/arid1a', 'pipelines_dir': '/home/arendeiro/workspace/pipelines', 'results_subdir': 'data'}
Parsing relative sections
Ensuring absolute path(s) for 'submission_subdir'
Ensuring absolute path for '/scratch/lab_bock/shared/projects/arid1a/submission'
Already absolute
Setting 'submission_subdir' to '/scratch/lab_bock/shared/projects/arid1a/submission'
Ensuring absolute path(s) for 'merge_table'
Ensuring absolute path for '/scratch/lab_bock/shared/projects/arid1a/metadata/merge_table.csv'
Already absolute
Setting 'merge_table' to '/scratch/lab_bock/shared/projects/arid1a/metadata/merge_table.csv'
Ensuring absolute path(s) for 'sample_annotation'
Ensuring absolute path for '/scratch/lab_bock/shared/projects/arid1a/metadata/annotation.csv'
Already absolute
Setting 'sample_annotation' to '/scratch/lab_bock/shared/projects/arid1a/metadata/annotation.csv'
Ensuring absolute path(s) for 'output_dir'
Ensuring absolute path for '/scratch/lab_bock/shared/projects/arid1a'
Already absolute
Setting 'output_dir' to '/scratch/lab_bock/shared/projects/arid1a'
Ensuring absolute path(s) for 'pipelines_dir'
Ensuring absolute path for '/home/arendeiro/workspace/pipelines'
Already absolute
Setting 'pipelines_dir' to '/home/arendeiro/workspace/pipelines'
Ensuring absolute path(s) for 'results_subdir'
Ensuring absolute path for '/scratch/lab_bock/shared/projects/arid1a/data'
Already absolute
Setting 'results_subdir' to '/scratch/lab_bock/shared/projects/arid1a/data'
Ensuring project directories exist
Ensuring project dir exists: '/scratch/lab_bock/shared/projects/arid1a/data'
Ensuring project dir exists: '/scratch/lab_bock/shared/projects/arid1a/submission'
Adding sample sheet
Creating samples from annotation sheet
***Successfully imported pipelines***
merge: sample 'HAP1_ATAC-seq_WT_HIRA_Hairpin3_R2'; lane=3
merge: sample 'HAP1_ATAC-seq_WT_HIRA_Hairpin3_R2'; data_source=/scratch/lab_bsf/samples/BSF_0326_HHYG3BBXX/BSF_0326_HHYG3BBXX_3_samples/BSF_0326_HHYG3BBXX_3#R2_HAP1_WT_C631_shHIRA_3_S23330.bam
merge: sample 'HAP1_ATAC-seq_WT_HIRA_Hairpin3_R2'; data_source_key=bsf
merge: sample 'HAP1_ATAC-seq_WT_HIRA_Hairpin3_R2'; flowcell=BSF_0326_HHYG3BBXX
merge: sample 'HAP1_ATAC-seq_WT_HIRA_Hairpin3_R2'; BSF_name=R2_HAP1_WT_C631_shHIRA_3_S23330
...
```

**Comment by nsheff** [comment]
> [off topic: can we in the future have something like a looper.logger() function activate that? Maybe also a way to control verbosity e.g. looper.set_logging_level("DEBUG")?]

I was going to suggest this, too. We just need a quick function to turn on logging interactively, and some documentation on it.

**Comment by nsheff** [comment]
@afrendeiro can you look at whether the `__library__` attribute in your .`py` file match the `library` column in your annotation sheet exactly?

**Comment by afrendeiro** [comment]
Yes, both `__library__` and `library` match exactly. Like I said, this works in 0.5 so I'm really puzzled why it's failing now...

**Comment by nsheff** [comment]
Ok, revamping child subclasses seems imminent. Plan:

* use InterfaceManager to identify python scripts that may hold relevant subclasses, instead of current logic in `_find_sample_subtypes`.

init should be:

```
        self.interface_manager = InterfaceManager(self.metadata.pipelines_dir)
        #self.add_sample_sheet()  # old way
        self.sample_sheet = SampleSheet(self.metadata.sample_annotation)  # new way
        self.finalize_pipelines_directory()
```

The concept of a sample subclass is not inherent to a sample, but is relative to a sample-pipeline interaction. one sample may be able to be instantiated as multiple different subtypes, depending on the pipeline it is submitted to.

as such, we cannot just instantiate subclasses at project creation. instead, we should instantiate with generic subtypes, and then allow an easy interface to grab specialized child classes from the project by specifying a particular pipeline from the interface.

- pipeline_interface creation comes out of looper `main` because it's now handled in the Project `__init__`. 
- looper `run` doesn't need `pipeline_interface` as a parameter because the project is aware of this.
- project needs a new way of providing Sample subclasses, when given a particular pipeline?

it doesn't make sense to `import pipelines` because this overloads the `pipelines` namespace, and multiple repositories would have to be named the same thing, which won't work. therefore, the sample subclasses can't be imported from a global module, but must instead be imported from the pipeline files, uninstalled.

**Comment by nsheff** [comment]
See also Issue #130

**Comment by vreuter** [comment]
I got this to work now on an ATAC example using the style of #130 , so this may be ready for another test run
