### ISSUE TITLE
Idea: sample subclasses in pipeline interface

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#130]
Motivated by #129.

Right now there are 2 protocol-sample mappings: the protocol_mappings file, and then the `__library__` attribute in a sample subclass. This is a problem; if a user changes the protocol mappings, they cannot (easily) change the `__library__` attribute, and so they won't get the appropriate subclass.

Solution: 

We make it so that subclasses need not have a `__library__` attribute, but should just always be used by default. Any class in a `py` pipeline script that extends `Sample` will be used. This solves 95% of use cases, and leaves only 1 problem: What if a pipeline script needs to define two different subclasses for two different protocols?

In this case, the pipeline will need to map these subclasses to protocols NOT through the `__library__` attribute (as it does now), but instead through a new section in the `pipeline_interface` file, like so:

```
pipeline_interface:
  atacseq.py:
    sample_subclasses:
      dnase: DnaseSeqSample
      ATAC-seq: AtacSeqSample
```

This makes it modulated by the pipeline user at the level of the pipeline interface, instead of in the python code itself.

**Comment by nsheff** [comment]
discussed with @vreuter using `sample_subtypes` instead of `sample_subclasses`. I think subtypes is better.

**Comment by vreuter** [comment]
:+1: implemented in https://github.com/epigen/looper/pull/135
