### ISSUE TITLE
Generalize pipelines_dir

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#133]
The `pipelines_dir` section of project configuration files and the corresponding `Project` attribute has become multiple and polymorphic, allowing pointer(s) to folder(s) and/or file(s). The naming should be generalized.

First ideas:
`pipeline_pointers`
`pipeline_locations`
`pipeline_interfaces`
`pipelines`

This could wait until 1.0 and an immediate hard deprecation (simpler, but harsher) or be part of 0.7 and allow the current format until 1.0 (gentler, but harder).

**Comment by nsheff** [comment]
I actually think for 0.6 we need to allow 'pipeline_interfaces' _in addition to_ 'pipelines_dir' to ease transition. This should not be hard to do. What do you think?

**Comment by vreuter** [comment]
I'll not speculate about how straightforward it will or won't be. Such transitions always seem simple; sometimes they are, sometimes they aren't. I see no advantage to doing this when the change is a simple name swap. The need for logic rather than semantic change is to support backward compatibility. 

But the user space will likely be highly split. Virtually no one using the current system will migrate until forced, and any new users will adopt the new name. But processing a new name doesn't intrinsically necessitate a logic change, only if we're trying to wear two hats at the same time.

So I'm fine with making the changes, but I'm not in favor of the idea.

**Comment by nsheff** [comment]
I solved this pretty easily in  	13d553b --
basically it does this:
if you provide 'pipelines_dir', it just kindly prompts a switch 
if you provide 'pipeline_interfaces', it works as normal.
 If you provide both, it throws an error and suggests deleting pipelines_dir.

it's a nice temporary forwards-and-backwards solution.
