### ISSUE TITLE
Updated requirements

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#134]
v0.6 introduced a new requirement on pandas 0.20.1 and numexpr... was it 2.26?

* [x] update requirements so installs automatically update pandas and numexpr
* [x] add new requirement to changelog.

**Comment by vreuter** [comment]
Pandas bound on 0.20.2 is indeed the numexpr culprit https://pandas.pydata.org/pandas-docs/stable/install.html#install-recommended-dependencies

**Comment by vreuter** [comment]
Want me to just include this on the RC2 branch?

**Comment by nsheff** [comment]
This is solved in #135.
