### ISSUE TITLE
TypeError in v0.6-rc1

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#137]
reported by @rcorces

In python 3, we get an error : `TypeError: unorderable types: sttr() > int()`
from looper.py line 353: `if submit_settings.setdefault("cores", 1) > 1:`

argument seems to be getting passed as a string.

fixing it like so works:
```
if int(submit_settings.setdefault("cores", 1)) > 1:
                    cmd += " -P " + submit_settings["cores"]
                try:
                    if int(submit_settings["mem"]) > 1:
                        cmd += " -M " + submit_settings["mem"]
```

**Comment by vreuter** [comment]
Yes thanks @rcorces @nsheff this has been addressed in the rc2
