### ISSUE TITLE
Display subcommand description in its own help text

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#138]
With `looper --help`, I can see the description for each available CLI program. While not critical, it'd be nice to also have this description with `looper <subcommand> --help`.

**Comment by nsheff** [comment]
I don't follow -- this is how it works already, isn't it? try `looper run --help` for example.

or are you saying `looper run --help` should show you the `summarize` option? If so, I disagree.

**Comment by vreuter** [comment]
```
(looper2) vpr9v @ cphg-5L9SYF2 ~/code/looper (0.6-rc2)
└─ $ ▶ looper --help
version: 0.6.0-rc2
usage: looper [-h] [-V] {run,summarize,destroy,check,clean} ...

looper - Loop through samples and submit pipelines.

positional arguments:
  {run,summarize,destroy,check,clean}
    run                 Main Looper function: Submit jobs for samples.
    summarize           Summarize statistics of project samples.
    destroy             Remove all files of the project.
    check               Checks flag status of current runs.
    clean               Runs clean scripts to remove intermediate files of
                        already processed jobs.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit

For subcommand-specific options, type: 'looper <subcommand> -h'
https://github.com/epigen/looper
(looper2) vpr9v @ cphg-5L9SYF2 ~/code/looper (0.6-rc2)
```

**Comment by vreuter** [comment]
I just mean that it'd be nice to see the description that's here for say, `run`, when we do `looper run --help`

**Comment by nsheff** [comment]
Agreed.

@vreuter if you can take a quick look at this and implement it for 0.6 that would be great. It fits nicely with our other help docs/usage updates. You could grab the text from the current dev usage page. I don't know how hard this would be to do. if it's not super simple then we punt it to 0.7.

**Comment by vreuter** [comment]
Yep, it wound being pretty straightforward, so it's in #151
