### ISSUE TITLE
Revisit sample subclasses as dict vs series

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#142]
Raised by @vreuter  in #135:

> One note on the Sample subclasses that I noticed during this round of changes...it seems like some of the Sample subclass constructors assume that the input data is a Series. This became apparent when I'd represented a generic Sample as an ordinary dict and then passed that data through to the subtype constructor(s) within looper.run. This works fine, having Series be the base type that's passed, but in general I think it may make more sense to have the Samplesubclass constructors also operate on a normal dictionary and/or an Iterable of two-tuples since they're more basic/builtin types. This could lower the barrier to someone using a Sample, eliminating a need for familiarity with pandas.

**Comment by vreuter** [comment]
On the `looper` / `models` side, the base `Sample` constructor can handle a `Sample`, a `Series`, or an ordinary `Mapping` as the primary source of data, so this is all set on the `looper` side. It's up to pipeline authors to decide whether they want to do any type checking in their subclass(es) before invoking the base class constructor.
