### ISSUE TITLE
Logging info in CLI help

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#145]
From @afrendeiro 

> Could there be an easy way to let the user see some of the logging options in the CLI without cluttering too much the --help message? Right now one has to look at the code to activate more verbose logging...
the `--dbg` option doesn't seem to do anything for me, I still get the same amount of detail. When using the interactive session however (as described in #129), I do get more detail.

In the information provided, describe the requirement on the location of `--dbg` within the command in order to get the desired effect.

**Comment by vreuter** [comment]
From @nsheff 
https://github.com/epigen/looper/issues/144#issuecomment-314164239
> this would be really great; then we only maintain the docs right in place and then auto-generate the readthe docs; it's suppressed by default but accessible on the CLI if someone wants. keeps general use help uncluttered. I think this solves all issues. name ideas? --adv-help ? Meh...

`--help-details`

**Comment by nsheff** [comment]
see dev readthedocs:

http://looper.readthedocs.io/en/dev/usage.html

**Comment by afrendeiro** [comment]
Sorry to bug you again with this, but I still feel that the current `--details` option to see the debug options is not really necessary (i.e. these options should be shown all the time) and currently the line saying there is a `--details` option is too hidden (it's the last line on the help and is missing a newline before it.).

**Comment by nsheff** [comment]
alright, sounds fine to me I guess. in the current form the debug options are much less substantial than they used to be.

So if you want to either 1) make `--details` easier to find or 2) eliminate `--details` altogether, that's fine with me.

make sure you re-run the usage docs updating script to change the [usage page](http://looper.readthedocs.io/en/dev/usage.html) automatically

**Comment by nsheff** [comment]
@afrendeiro what's the status on this issue?

**Comment by afrendeiro** [comment]
I would vote for 2), remove details and add the remaining 2 optional arguments to the general `--help`.

**Comment by nsheff** [comment]
fine with me. are you going to do that @afrendeiro ?

**Comment by vreuter** [comment]
I'm happy to do this; I have some active changes on `dev` and can incorporate. If you want to do it, though, let me know @afrendeiro and I'll freeze `dev`, branch off, then suspend direct pushes to `dev` (from me).

**Comment by afrendeiro** [comment]
Sure, @vreuter please go ahead.
