### ISSUE TITLE
Advanced logging options documentation and CLI subcommand

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#148]
@nsheff replying to @afrendeiro 

> Logging:
Could there be an easy way to let the user see some of the logging options in the CLI without cluttering too much the --help message? Right now one has to look at the code to activate more verbose logging.

> I propose: a detailed documentation page in readthedocs, with a note in the CLI help message.

**Comment by vreuter** [comment]
Implementation proposal from @nsheff : https://github.com/epigen/looper/issues/144#issuecomment-314164239

**Comment by vreuter** [comment]
So I think I understand what your original comment means @nsheff but I want to clarify. So is the idea to to have another rst document in the `doc/source` folder that describes the finer-grained logging CLI options, and then just have the `--help-details` program parse that file and print the text in the console?

**Comment by nsheff** [comment]
No -- the opposite. The .rst file should be generated by running `looper --help` and `looper --help-details`. I'm happy to implement this

**Comment by nsheff** [comment]
:grin:

I just already know exactly how I want to do it, so it will be easier to just do it than to try to explain.

**Comment by vreuter** [comment]
Ha yeah :100:  glad I clarified before trying to implemented

**Comment by nsheff** [comment]
ok give it a go.
try `looper --help --details`

and try running `./update-usage-docs.sh`
