### ISSUE TITLE
"SampleName" as the new "sample_name"

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#155]
Looking at other code, it seems like `"SampleName"` is the header field / column name used in data from the SRA (maybe also ENA then?) If so, it could be convenient to use this as the required attribute in a couple of places where it's checked (off hand, as a `Sample` attribute, and as a key/column in the sample annotations sheet that `looper` reads). There's already some groundwork in place that would simplify this transition. Namely, that `"sample_name"` is stored as a constant, and that there's an alias for the relevant `Sample` attribute (`name` for `sample_name`).

**Comment by nsheff** [comment]
it's a good thought -- and we actually knew this at the very beginning. but we elected to go with underscores anyway, and now I think it's too deep in to change (all looper projects created so far, which is a lot, use `sample_name`, so there's no going back...)
I think get_geo fixes this for data coming directly from SRA.

so, for better or worse, we have decided that the column names would use lowercase and underscores, and I think that's permanent at this point...

**Comment by vreuter** [comment]
OK

**Comment by vreuter** [comment]
I think `get_geo` leaves it as `"SampleName"` (I'm working now with metadata generated by `get_geo` now), but maybe that's something we could add.

**Comment by nsheff** [comment]
yeah, could be useful. 

I thought as a python guru you would be a staunch advocate of `sample_name` :smile:

**Comment by vreuter** [comment]
Ha I'm getting used to more back-and-forth between Python and R, and just generally seeing more style crossover. You're right, though, a few months ago I probably would've been more adamant about that ;D
