### ISSUE TITLE
Looper cannot handle multiple partition submission

### ISSUE THREAD

**Issue by rcorces** [epigen/looper#164]
Slurm has the ability to accept a comma-delimited list of partitions. You can submit to:
--partition=normal,long and the job will run on whichever partition it can first

At least in my limited testing, this isnt possible with looper (see below, KeyError). This seems like it would be an easy fix?

```
[mcorces@sh-ln02 login! /scratch/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602]$ looper run --compute howchang,owners ./config/170714_TCGA_A602_config.yaml 
Command: run (Looper version: 0.6.0-rc1)
Creating Project from file: './config/170714_TCGA_A602_config.yaml'
Loading PEPENV: /share/PI/howchang/users/mcorces/tools/python/virtualenv/python-2.7.13/lib/python2.7/site-packages/looper/submit_templates/default_compute_settings.yaml
Loading PEPENV: /share/PI/howchang/users/mcorces/tools/pepenv/stanford.yaml
Parsing Project config file
Results subdir: /scratch/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/results_pipeline
Traceback (most recent call last):
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-2.7.13/bin/looper", line 11, in <module>
    load_entry_point('looper==0.6.0rc1', 'console_scripts', 'looper')()
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-2.7.13/lib/python2.7/site-packages/looper/looper.py", line 800, in main
    prj.set_compute(args.compute)
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-2.7.13/lib/python2.7/site-packages/looper/models.py", line 812, in set_compute
    self.compute.add_entries(self.environment.compute[setting])
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-2.7.13/lib/python2.7/site-packages/looper/models.py", line 268, in __getitem__
    raise KeyError(item)
KeyError: 'howchang,owners'
```

**Comment by vreuter** [comment]
@nsheff it seems like this contravenes the notion of a resource bundle and would be a case for which it'd be tricky (or impossible) to create a submission script? Caveat: I have limited SLURM knowledge.

**Comment by rcorces** [comment]
I may be wrong but I think that all you have to do is allow the --compute parameter to accept a comma-delimited list and pass this for the --partition parameter of the submission file.
This would be a valid submission:
```
#!/bin/bash
#SBATCH --job-name='mySubmission_ATACseq.py'
#SBATCH --output='output_ATACseq.log'
#SBATCH --mem='32000'
#SBATCH --cpus-per-task='16'
#SBATCH --time='11:00:00'
#SBATCH --partition='long,normal'
#SBATCH -m block
#SBATCH --ntasks=1
```

**Comment by vreuter** [comment]
Yeah that's how interpreted what you were saying. Sorry, I think my point was poorly raised. What I was trying to say is that such a submission script implies the same resource request for memory/cores/time for both of those different partitions, which has seemed to not be the case in the config files I've seen. It's not that it's not possible I guess, or even not desirable, just that it seems to suggest a lack of coupling between partition and resources. I don't know about the extent to which that does or doesn't reflect a typical cluster configuration, though.

**Comment by rcorces** [comment]
I see. Thats a fair point. On our cluster, we have "owner" nodes (partition = howchang) that you purchase and you get priority access to. This also gives you access to the nodes of other owners while they arent using them (partition = owners). The nodes are configured identically. So to make the most of resources, you can prioritize your jobs to submit to your owner partition (howchang) and if that isnt available submit the job to the partition of other owners' nodes (owners). The jobs on the partition "owners" can be preempted.

my example of using "long" and "normal" was a poor choice.

**Comment by nsheff** [comment]
@rcorces You're confusing the resource bundle name (a looper thing) with the partition name (a slurm thing).
In many examples we make these the same thing, because it makes sense, but they are not. You need to define a resource bundle (named whatever you want, let's call it `dualpriority` for kicks) in your `pepenv.yaml` file, which you say `partition: howchang,owners`. Then on the command line you say `--compute dualpriority`.

Right now you're indexing into this file with an index called "howchang, owners": https://github.com/pepkit/pepenv/blob/master/stanford_sherlock.yaml

but the only possible indices are: `defaullt`, `local`, `normal`, `dev`, and `bigmem`. See how those just *happened* to map exactly to the value under `partition`? That's where the confusion comes from. Define a new one like this:

```
compute:
  dualpriority:
    submission_template: templates/slurm_template.sub
    submission_command: sbatch
    partition: "howchang, owners"
```

make sense?

**Comment by nsheff** [comment]
So just for clarity: you **cannot** specify two compute bundles to looper on the command line. but you (I think) **can** specify multiple partitions within a compute resource bundle, which solves your use case better, in fact.

**Comment by nsheff** [comment]
@vreuter I think your point still stands, though I don't think it is exactly what's going on here... actually, resources requested (defined in pipeline interface) are already decoupled from partition (defined in compute config), so it's *already* the user's responsibility to choose the right partition for the resources.

But really, it's solved by the flexibility of the compute bundles. Users can really do whatever they want -- looper doesn't prevent you from using SLURM however you want to. You just define your compute settings (or templates or whatever) exactly how you want. looper is really transparent in this case, it imposes no extra restrictions on how you want to use slurm. I think that's the way it should be.

**Comment by rcorces** [comment]
you're absolutely right! sorry about that. I was confusing the resource compute bundle with the partition. great! so I'm closing this because its not an issue.
