### ISSUE TITLE
Feature Request: Catch job submission errors?

### ISSUE THREAD

**Issue by rcorces** [epigen/looper#167]
Not sure if this one is easy or not. This is definitely an end-user issue. I was just trying to submit a bunch of jobs with looper at the same time (>50) and 2 of the jobs werent actually getting submitted but looper was saying that they were getting submitted.

Because the output of looper is pretty heavy, I had a ton of trouble sifting through it to figure out what was going on. Turns out I was requesting an impossible combination of resources for those two jobs (because those input files happened to be bigger than the rest).

Those jobs were failing submission with sbatch errors. The sbatch errors were reported in the looper output but looper was saying that they had been submitted (which, technically speaking, they had been, but immediately failed). If looper could catch these errors and report them in the final line, that could be helpful.

**Comment by nsheff** [comment]
makes perfect sense.

we should definitely be able to capture the return value of whatever command we execute (in this case `sbatch` and use that to modulate looper's submission summary.

good catch.

**Comment by vreuter** [comment]
I remember a conversation about this sort of thing...the impossibility or peering into a user's cluster configuration, and the intractability of predicting or enumerating all of the possibilities. This seems like a great way to accomplish almost the same end result, in a fashion that's actually feasible :+1:

**Comment by nsheff** [comment]
@rcorces This is now implemented in 0.7. thank @vreuter
