### ISSUE TITLE
Discussion: messaging about missing data source entry

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#173]
Stems from https://github.com/epigen/looper/issues/171
From @nsheff 
 >this solves it for the case that it is intended, but is it possible that we do want at least a single warning for cases where it really is missing and that's unintended?
"This" is https://github.com/epigen/looper/pull/172
@vreuter :
>How would a `Sample` infer intent?

**Comment by nsheff** [comment]
exactly my point-- it can't. we can't assume that a missing key is intended, which is what this change does.

**Comment by vreuter** [comment]
> collated into a single notice per bad key

is what's already happening. Each message is from a myopic `Sample`, so it has no idea that there are others encountering the same thing.

**Comment by nsheff** [comment]
I think we realized that this error was actually extra, so the downgrade solution did solve the problem, because there's a separate project-level collated error that happens later, correct? So I think this can be closed.

**Comment by vreuter** [comment]
That sounds right, but I don't concretely remember.

**Comment by nsheff** [comment]
Well, let's live on the edge then and close it.

**Comment by vreuter** [comment]
:fire:
