### ISSUE TITLE
Failure message styling

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#176]
Currently, an errors cause by missing file(s) are regarded as different errors in the failure messaging if the missing files are different. Is this the desired behavior, or do we want the notion of "missing files" to be bundled as a single error?
```
Samples by failure:
Missing file(s): /home/vpr9v/code/microtest/data/RNA_TRUseq_50SE.bam: SMART-seq_human_truseq_SE, SMART-seq_human_truseq_SE
Missing file(s): /home/vpr9v/code/microtest/data/quant-seq_SE.bam: Quant-seq_human, Quant-seq_human
Missing file(s): /home/vpr9v/code/microtest/data/RNA_SMART_50SE.bam: SMART-seq_human_SE, SMART-seq_human_SE
```

**Comment by vreuter** [comment]
What's your opinion @nsheff and @afrendeiro ?

**Comment by nsheff** [comment]
I vote for bundling as a single error. but we need to make sure that the path of the missing file is somehow conveyed, if we remove from the error string.

**Comment by nsheff** [comment]
Actually I think the path may be conveyed already in another print message, but would need to double-check.

**Comment by afrendeiro** [comment]
Yeah, bundling sounds better

**Comment by vreuter** [comment]
Cool, I think so, too. :tada: consensus! :tada:

**Comment by vreuter** [comment]
Seems to be solved with https://github.com/epigen/looper/commit/e57fba5c69703af42e03080b67bc82e1370174e5
