### ISSUE TITLE
looper check implementation

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#177]
Raised by @rcorces

> whenever I run looper check, it always reports statistics for all folders in the results directory, not just the samples that correspond to the annotation file that is detailed in the config.yaml file.
Is this really the desired behavior? I know its pretty easy to just use the ls | xargs | sort | uniq one-liner but doesn't it seem like the correct behavior would be to only report the status of samples associated with the annotation.csv file?

He is right. the current implementation of `looper check` is just looking at the project output folder, and then running an `ls` to get all subfolders. It should instead actually build the project and then loop through each samples in Python, instead of using the shell.

**Comment by rcorces** [comment]
I'll also add that I definitely see value for having the ability to check the status of all subfolders of the results directory. It just seems like the default behavior of "check" should mimic the other looper functions like "run" which only act on the samples in the annotation file. So maybe an ideal implementation would allow for both. Perhaps something like an optional argument "-a" for "report all subfolders in the results directory"

looper check config_file
only outputs the status of the samples in the annotation file detailed in the config file

looper check -a config_file
outputs the status of all samples in the results dir detailed in the config file
