### ISSUE TITLE
error message wording

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#180]
two related issues, just relating to presentation clarity for a new person

1. when pipeline is missing, I get: `Missing pipeline script: '/home/nsheff/code/sratofastq/fastq-dump'`

this is also happening if I give something that is in PATH. it should also check PATH. (right now it will require an absolute path). this error is also printed twice.

2. When this pipeline script is reported missing, it's giving this error for each sample:
`> Not submitted: No submission bundle for protocol`

I think we should think how to present this error message. I even am not sure what is meant by "submission bundle". This is the wrong message for this error, and also, I think we could rename it anyway, even for when it's the right message.

thoughts?

**Comment by vreuter** [comment]
I don't have a name preference.

**Comment by nsheff** [comment]
I figured out what triggers this error. This is coming up when the protocol is not present in the pipeline interface.

So I would suggest:

```
Protocol 'x' is not specified in pipeline interface
```

Where 'x' is replaced with that sample's protocol

**Comment by nsheff** [comment]
Or, maybe just 
```
Protocol missing in pipeline interface
```

**Comment by vreuter** [comment]
It should be gone in the latest `dev`; now solving this one https://github.com/epigen/looper/issues/191 would also imply a solution to this I think.

**Comment by nsheff** [comment]
great, this is fine then now.
