### ISSUE TITLE
Allow derivation of values for an implications-bearing column

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#181]
Right now, it appears that columns are derived, and then implied.

What if you want to derive an implied column? I'd like to do that now.

Is there any disadvantage to swapping the order?

**Comment by vreuter** [comment]
What's the use case?

**Comment by nsheff** [comment]
I'd like to set a new sample attribute, constant for all samples. it should be derived from other attributes.

Since it's constant, I should do this at the project level, not by adding a new column to the annotation sheet. There's no way to do that.

**Comment by vreuter** [comment]
I'm not sure I totally get what you mean, but if I do, this feel like two related but distinct issues.
One is how to specify a derived value as an attribute/column with implications, and the other is how to denote a "for all samples" notion for a column implication.

I guess my main question is: are you saying that you want to derive the _name_ for an attribute to attach to each Sample, to which a fixed value will be assigned, or you know the name and you want to derive the single, homogeneous _value_?

**Comment by nsheff** [comment]
> I guess my main question is: are you saying that you want to derive the name for an attribute to attach to each Sample, to which a fixed value will be assigned, or you know the name and you want to derive the single, homogeneous value?

I see no value (and some harm) in making a variable *name*. I'm attempting to do the latter.

We can revisit this in the future, it's bigger question I think.

**Comment by vreuter** [comment]
Whew :relieved: ! I thought the first way may be possible but seemed strange. The value way makes much more sense. OK, so no downside immediately comes to mind. I think that col/attr inference comes after derivation in `set_file_paths` simply because the implications are a newer feature.

**Comment by vreuter** [comment]
I'm ok with leaving as 0.8, but with clearer understanding I'm also fine with going to 0.7 for this. `implied_columns` is new _enough_ that it doesn't feel like something with far-reaching ramifications. What do you think?

**Comment by nsheff** [comment]
let's revisit as we get closer to releasing 0.7 and see where we are

**Comment by vreuter** [comment]
OK. The more I've looked at `set_file_paths`, the less troublesome inverting the execution sequence seems.
