### ISSUE TITLE
sample import check warnings should only be done for .py pipelines

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#184]
we've been focused on `.py` pipelines, but this may not be true. I got this error:

> Using base Sample because of failure in attempt to import pipeline module '/usr/bin/fastq-dump': SyntaxError("Non-ASCII character '\\x80' in file /usr/bin/fastq-dump on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/usr/bin/fastq-dump', 1, 0, None))

I think this makes sense to output if my pipeline was written in python, but for non-python pipelines, we probably don't even need to try to import them, and even if we do, we shouldn't output this notice.

**Comment by vreuter** [comment]
Can you try with https://github.com/epigen/looper/commit/49151745d058d3cba8ef79e0938a767ce217c0db

**Comment by nsheff** [comment]
Yep. that fixed it.
