### ISSUE TITLE
looper speed

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#186]
I've noticed in my tests today that looper seems to go really slowly through the samples. When turning on debug it's clear that it pauses for a split second on every sample right at this debug line:

```
models:1271 (_merge_samples) [DEBUG] > Setting sample data path
```

I'll keep looking into this but wanted to flag it. I think we should see if there's something simple in there we can eliminate to speed it up again. it used to feel faster.

**Comment by vreuter** [comment]
Yeah, I noticed it, too. I think it's from `Sample` extending `AttributeDict` rather than `object`.
Maybe more data volume in the I/O operations and maybe more time-intensive conversion of nested mappings for the `to_yaml` step? That was my guess.

**Comment by vreuter** [comment]
I went with that as the resolution to https://github.com/epigen/looper/issues/63#issuecomment-285116174 but am also fine with going back to `object` + `__getitem__`. Your call.

**Comment by nsheff** [comment]
Interesting. I don't know why that would slow it down so much... I like `Sample` extending `AttributeDict`...

**Comment by vreuter** [comment]
Isn't each ordinary `dict` in an `AttributeDict` converted also to `AttributeDict`? Then also there's slightly more conditional logic in the `to_yaml` stage.

**Comment by vreuter** [comment]
For me, the effect is less significant for, say, `run` on `microtest` than for the units. Still noticeable, but not nearly as bad. The extent `Sample` creation and disk action happening in the tests, along with those facts about how `AttributeDict` works and is handled by `Sample`, led me to that thought. And that's when I first got the slower tests.

**Comment by nsheff** [comment]
still, these things seem like they should be tiny. I mean, we're not talking about any major processing here... this is like, what, looking up 10-20 attributes on 10-20 objects? This should *not* be a computational burden. 

I mean, it's probably right, but it's then that I don't understand something about what costs time in python.

**Comment by vreuter** [comment]
Yeah I'm not sure how time-costly (or how varied) the custom object creation overhead is.
Check out the difference between these guys, though:
f5b4688840a046fe9b18fa8502a6e70af5f8fa35
51a4b1bd0654e3e87c8f3af7a243e29c570af243 (1 newer)

**Comment by vreuter** [comment]
The test speed diff, that is

**Comment by nsheff** [comment]
on my real example, I get 3 seconds for the first commit, and then at 20 seconds the 2nd one bails on me. 

I think it has something to do with serialization, and maybe some recursion issues in there

**Comment by nsheff** [comment]
can you test if you just turn off the serialization if that fixes it?

**Comment by vreuter** [comment]
Can you post the traceback? On both commits, the test successfully complete.

**Comment by vreuter** [comment]
I'm not sure what you mean by turn off the serialization, though. `to_yaml` is a method on `Sample`. Deleting it will definitely break anything that routes through `looper` itself.

**Comment by nsheff** [comment]
> I'm not sure what you mean by turn off the serialization, though. to_yaml is a method on Sample. Deleting it will definitely break anything that routes through looper itself.

I just meant maybe making the `to_yaml` function a dummy (so have it just return, basically nothing) to see if that's where the time sync is. but maybe I don't understand it well, sorry

**Comment by nsheff** [comment]
> Can you post the traceback/failure(s)? On both commits, the test successfully complete.

This was with my real example, which ran into a problem that was later fixed

**Comment by vreuter** [comment]
Tests are back to ~6s for me, so I'm closing but please reopen if this comes up again

**Comment by nsheff** [comment]
great -- but wait, what was the problem? how did this fix it?

**Comment by vreuter** [comment]
There were several logging calls for each `__setitem__` call on `AttributeDict`. Even though they were below even debug level, I think that the creation and routing/handling logic for each one was slowing it down. It wasn't too bad before, but there are just way more `__setitem__` calls with `Sample` extending `AttributeDict`, so I just removed the calls. They were more useful when `AttributeDict` was less stable but not worth the time cost now. To see them required setting the logging level beneath debug anyway.
