### ISSUE TITLE
Check PATH for "pipeline script" or whatever is to be run

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#188]
Reported by @nsheff 
>1. when pipeline is missing, I get: `Missing pipeline script: '/home/nsheff/code/sratofastq/fastq-dump'`
this is also happening if I give something that is in PATH. it should also check PATH. (right now it will require an absolute path)

**Comment by nsheff** [comment]
this is still not working for me. if you change a path to `ls` you get:

```
Missing pipeline script: '/sfs/nfs/blue/ns5bc/code/pepsra/sra_convert/ls'
Missing pipeline script: '/sfs/nfs/blue/ns5bc/code/pepsra/sra_convert/ls'
No mapping for protocol: 'ChIP'
No mapping for protocol: 'other'
## [1 of 27] Hi-C_H1_embryonic_stem_cells_replicate_one (other)
> Not submitted: No pipeline for protocol
## [2 of 27] Hi-C_H1_embryonic_stem_cells_replicate_two (other)
> Not submitted: No pipeline for protocol
```

**Comment by vreuter** [comment]
Ahhh I bet the `path` value is being converted to absolute before it's being checked as a command-line program

**Comment by vreuter** [comment]
OK, I tried with `pepsra` and it seems to be working. Let me know whenever you try again whether it remains troublesome for you.
