### ISSUE TITLE
allow wildcard protocol mappings

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#191]
we should support an asterisk, to map all samples to a particular pipeline:

```
protocol_mapping:
  "*": convert
```

**Comment by vreuter** [comment]
OK, the latest dev commit seems to be permitting this; when you get a chance, can you confirm?

**Comment by nsheff** [comment]
Confirmed.

**Comment by vreuter** [comment]
Yep, good catch. Do we want the message with each sample, or prior to that, with the Project creation stuff? The "Unknown protocol" one comes from when the pipeline interfaces defined in the project are investigated for which protocols they support. The "No mapping..." one comes from during the sample processing.

**Comment by vreuter** [comment]
Actually, reverse that; "Unknown protocol" comes during sample iteration, "No mapping" from parsing the interfaces

**Comment by nsheff** [comment]
Also as an aside, I think these two messages are redundant:
```
Protocols: ChIP, other
Building submission bundle(s) for protocol(s): ChIP, other
```

**Comment by vreuter** [comment]
> neither of these messages is coming during the sample printouts; they are both before (maybe at sample creation?)
You're right; I'd been looking just in `looper.py`, not `models` also

**Comment by vreuter** [comment]
OK, let me know what you think on the most recent commit.

**Comment by nsheff** [comment]
Ok. Everything looks great.

Two questions:
1. I see:
```
No resources for pipeline 'convert'
```

But that is false. There are resources for pipeline 'convert'.

2. Do you want the `No mapping for protocol: ...` to show up when an asterisk is present? Either way is find with me I guess.

**Comment by nsheff** [comment]
> But that is false. There are resources for pipeline 'convert'.

I take that back. it was at the wrong indentation. My bad.

**Comment by vreuter** [comment]
I don't want it to be there for the `"*"`; there was still a second place for that message to come up, but it should be gone now.
