### ISSUE TITLE
derived columns and merge tables

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#21]
derived columns in merge tables appears to be not implemented yet...

**Comment by afrendeiro** [comment]
How can I reproduce that?

Could it be that now is broken and not that it was not implemented?

Before the latest changes I had been building paths to input files in the merge table using the `data_source` column - that was by default a derived column, so I guess it was implemented.

**Comment by nsheff** [comment]
Only `data_source` worked... generic `derived_columns` were never implemented... 

with my latest commits, now it works.
