### ISSUE TITLE
make_project_dirs is broken

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#24]
@afrendeiro 

looper calls `Project.make_project_dirs()`, which apparently creates a new folder for every attribute in `metadata` -- why?

I for example have missing files in one project, which now have random folder created in my repository.

Can this be opt-in instead of opt-out?

**Comment by nsheff** [comment]
This is likely a relic of merging `paths` and `metadata`. Is this proposal acceptable?

**Comment by afrendeiro** [comment]
Yes, correct. Thanks!
