### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by mtugrul** [epigen/looper#26]
I tried to install looper by using pip in the cemm server (with --user), but it failed with this error message:

PermissionError: [Errno 13] Permission denied: '/cm/shared/apps/RSeQC/2.6.4/cm/shared/apps/python/2.7.6/lib/python2.7/site-packages/RSeQC-2.6.4-py2.7.egg-info/PKG-INFO'

I have already tried with different python and pip versions, but did not work out. Does anyone know how to handle this, or an alternative (without pip) installation?

**Comment by afrendeiro** [comment]
Hi Murat,
This doesn't seem to have anything to do with which version of python or looper you're using but with other software you have loaded in the cluster. You can test this by installing inside a virtualenvironment (like [here](https://github.com/epigen/microtest) for example).

RSeQC causes problems frequently with other libraries and I'm not sure why. Try unloading this module.

**Comment by mtugrul** [comment]
Yes, unloading RSeQC solved the problem. Thanks.
