### ISSUE TITLE
tsv sample annotations files

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#27]
looper will choke on a tsv and give an incoherent error: (sample_name column doesn't exist).
instead it could probably be made to parse a tsv as well as a csv, or at least warn that the tsv needs to switch to a csv.

**Comment by afrendeiro** [comment]
We could simply switch to pandas.read_table to read the annotation sheet which tries to determine the separator of a file. The read_csv and read_table functions are almost identical.

Optionally/additionally, we could implement a new CLI option that specifies the separator character and would be passed on: `pandas.read_csv(..., sep=args.sep)`.

**Comment by vreuter** [comment]
I think the main difference between the pandas parsers is with regard to default header parsing behavior. We may have to take care to make sure we get the desired header handling, but yeah it'd be nice to just get the separator inference that way.

**Comment by nsheff** [comment]
I would rather it just automatically guess either tsv or csv without having to specify.
I think if the `read_table` idea gets both csv and tsv headers right, we should do that.
