### ISSUE TITLE
AttributeDict construction

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#29]
The constructor, via `AttributeDict.add_entries`, ignores null values, causing tests for `AttributeDict` to fail when `None` is the value in the mapping that's the argument to the constructor.

**Comment by nsheff** [comment]
So this means if an entry key has a null value, the attribute will not be added to the `AttributeDict`; **not** that it will be added but with a `null` value...

**Comment by vreuter** [comment]
We talked a bit about this yesterday @nsheff , but I don't think that we reached a decision. Should null values continue to be ignored since this is a special data type, or is the preference to make it more like builtin `dict` and allow nulls? What do you think @afrendeiro ?

**Comment by nsheff** [comment]
I think probably null values should be added and allowed...

**Comment by vreuter** [comment]
Sounds good!
