### ISSUE TITLE
add sample sheet

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#3]
shouldn't add_sample_sheet happen inside `init` instead of having to be called explicitly?

**Comment by afrendeiro** [comment]
Could be - no strong opinion. Explicit is no harm though.

**Comment by nsheff** [comment]
it's just simpler; can you think of a case you'd ever want to construct looper, but not run `add_sample_sheet` ? if not, there's no reason to decouple them. and if so, there's still possibly no reason to decouple them if we can handle that case as a default or exception.

**Comment by afrendeiro** [comment]
Like I said, no preference really - go ahead if you want.
