### ISSUE TITLE
AttributeDict dict-like methods

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#31]
As I was trying to add test code, I noticed that things like making assertions about length for `AttributeDict` can't be done since it extends `object` and doesn't implement `__len__`. I'm new to the project, so maybe this is a deliberate design decision that was made? If not, though, I think that it could reduce confusion to implement things like `__len__`, and also comparisons. Currently, for instance, `AttributeDict({}) == {}` fails since `AttributeDict` doesn't implement `__eq__`. A way to simplify things like this may be to extend builtin `dict` and then override the behavior that we want to change. It seems like that inherit-and-override model would be more straightforward than recreating some of the builtin `dict` functionality, and it would please all of the POLA folks out there.

**Comment by nsheff** [comment]
Not a deliberate decision; I think you're right that `AttributeDict` should extend `dict` instead of object.
