### ISSUE TITLE
AttributeDict exception types

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#32]
It seems a bit odd that `AttributeDict({})['a']` throws an `AttributeError` rather than `KeyError`. Is this to intimate to users that dot-notation is the preferred access method, to reinforce the functionality beyond `dict` that's being provided here, both, or just an implementation corollary? If it's the last of those, we could change wrap the `getattr` call in a try/except and raise `KeyError` in the exception case to make behavior align more with intuition.

**Comment by nsheff** [comment]
Agreed; it's probably the last of these... but won't this resolve itself if AttributeDict extends dict instead of object? then getitem can just not be overridden.

**Comment by vreuter** [comment]
Yep :bird: :bird: :gem:

**Comment by vreuter** [comment]
Will be linked with https://github.com/epigen/looper/issues/31
