### ISSUE TITLE
flag-like pipeline_args parameters are not correctly passed to pipelines

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#42]
config section `pipeline_args` works correctly for arguments that have options (like `"--blah": blah`) but not for flags (like `"-D": null`).
This should work, but does not:
```
pipeline_args:
  default:
    "-D": null  # Use dirty mode by default for this project
  ATACseq.py:
    "-D": null  # Use dirty mode by default for this project
```

**Comment by vreuter** [comment]
Is this still true @nsheff ?

**Comment by nsheff** [comment]
Haven't tested recently...I will confirm...

**Comment by nsheff** [comment]
This is no longer a problem; it's working correctly now in `0.6-dev`
