### ISSUE TITLE
Using wildcard characters for read names in data_sources

### ISSUE THREAD

**Issue by rcorces** [epigen/looper#43]
In the "data_sources" section of the config file for looper, I dont think that it is currently possible to use wildcard characters to delineate read names. For example `"{sample_name}_*_R1*.fastq.gz"`.
Depending on how the fastq.gz file names are generated, this can be problematic. For example, one of our sequencing cores includes the barcodes in the fastq file name:
"GM12878-IlluminaTn5-A-MRC001-TGCTGGGT-TACTCCTT_S9_L001_R1_001.fastq.gz"
and
"GM12878-IlluminaTn5-B-MRC001-AGGTTGGG-TACTCCTT_S10_L001_R1_001.fastq.gz"
Since this will be different for each fastq file, it seems like you currently have to rename your fastqs or get creative with the data_sources input.
Being able to use wildcards would be great in this situation.

**Comment by nsheff** [comment]
This is a great idea. 

The current solution to this is to use a `merge_table`. instructions here: http://looper.readthedocs.io/en/latest/advanced.html#handling-multiple-input-files-with-a-merge-table

The advantage is flexibility: you can point to any file name anywhere. But this means you have to enumerate every file. That's how I'm doing it right now, but being able to use wildcards would be easier than having to define a merge table.

And it would be pretty easy, we just need to pass the derived column through `glob.glob()` I think for shell expansion...
