### ISSUE TITLE
looper fails on fastq inputs without read length specified

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#5]
read length should be optional. in this example, I'm using fastq inputs without read_length column. it can't detect it, so it throws an exception.

```
looper -c ~/code/microtest/config/microtest_config.yaml --sp bs
Remaining arguments passed to pipelines: []
Updating existing key: metadata
/home/nsheffield/.local/lib/python2.7/site-packages/looper/models.py:831: UserWarning: Detection of read type/length for fastq input is not yet implemented.
  print(_warnings.warn("Detection of read type/length for fastq input is not yet implemented."))
None
Traceback (most recent call last):
  File "/home/nsheffield/.local/bin/looper", line 9, in <module>
    load_entry_point('looper==0.1', 'console_scripts', 'looper')()
  File "/home/nsheffield/.local/lib/python2.7/site-packages/looper/looper.py", line 217, in main
    prj.add_sample_sheet()
  File "/home/nsheffield/.local/lib/python2.7/site-packages/looper/models.py", line 350, in add_sample_sheet
    sample.get_read_type()
  File "/home/nsheffield/.local/lib/python2.7/site-packages/looper/models.py", line 865, in get_read_type
    read_length = sorted(read_length)[-1]
TypeError: 'NoneType' object is not iterable

```

**Comment by nsheff** [comment]
also true for `read_type` (looper fails)

**Comment by afrendeiro** [comment]
I guess we should rename this to: "Implement read type/length detection for FASTQ input", or has there been any change to this since?

**Comment by nsheff** [comment]
I don't believe there has been a change... your solution is one idea, but also, read_length should just in general not be required, right? What if your pipeline doesn't care about read_length? why should looper demand that you provide it?

**Comment by afrendeiro** [comment]
I believe it is not required.
The original issue has probably to do with a part of the `Sample.get_read_type()` function assuming the `read_length` variable to be of a certain type (a list if I'm not mistaken) and trying to sort that, while in fact the `read_length` variable holds `None`, because checking read_length on a fastq file failed upstream.

This should be an easy fix actually, but it's a different issue than implementing checking read type/length for fastq inputs.

**Comment by nsheff** [comment]
I see. it just feels required because if it is not there, it crashes; but it is not explicitly required.

Yes, there are 2 different issues;
First, fix the implicit requirement (the bug above),
Second, (less important) implement automatic fastq read length assessment.

**Comment by afrendeiro** [comment]
Okay number 1 is fixed.

@nsheff Please remind me: for pipelines which input file is a paired-end FASTQ, how are we specifying this? Is there such a pipeline? Even if not it would be nice if we could make looper handle this.
At first sight this sounds like a particular case of "multiple inputs, one pipeline", but it isn't really because these aren't files to be merged and their order matters.

**Comment by nsheff** [comment]
Thanks. 

yes, this is how my atac-seq pipeline is; pypiper now has 2 input slots, --input and --input2. looper has been able to handle this for quite awhile now actually, it works great on both types of pipeline without issue.

it will also handle interleaved paired-end files (so, fastq, but only 1 file for both ends), I think all automatically, using the ngstk. all this logic was put in the `merge_or_link` and `input_to_fastq` functions in `ngstk`. Pipelines that use these will automatically handle any type of input, bam, paired-fastq, interleaved-fastq, zipped-paired-fastq, zipped-interleaved-fastq, single-end-fastq-, or zipped-single-end-fastq. at least that was my intent.

**Comment by nsheff** [comment]
Also, any of these can *also* have multiple inputs, which it merges appropriately in each case. I think this is all already implemented.

**Comment by afrendeiro** [comment]
Yes, but looper-side (before any pipeline and pypiper are started) how is this handled?
What does the user specify in the annotation sheet? How is it stored in the Sample attributes? I need to know this implement fastq checking.

**Comment by nsheff** [comment]
It's all totally flexible, just specified through derived columns as you want, as defined by the pipeline... I'm using "read1" and "read2".

I think this will need to be tied to required_inputs (see #10). -- you would just do the checking on anything in required_inputs?

**Comment by afrendeiro** [comment]
Okay, I understand now.
I had completely forgot about `required_inputs`. However there is a lot of confusion between derived columns and values holding input files, see #10, last comment.

**Comment by nsheff** [comment]
The new implementation that handles required attributes and relative attributes according to the pipeline interface solves this issue.

**Comment by ninamw** [comment]
Using "pip install --user https://github.com/epigen/looper/zipball/master" loads the older version that has this bug (looper fails on fastq inputs without read length specified)
Installing Pre-release version 'v0.4-rc2' resolved the issue. 
Thanks.

**Comment by vreuter** [comment]
May need your insight @nsheff on what inputs to use in 0.5 candidate to ensure that this isn't an issue there.

**Comment by nsheff** [comment]
@ninamw can you paste the actual error? was it identical to the above?

**Comment by ninamw** [comment]
Unfortunately I did not document the error log. 
The way I read it, it was a UserWarning that caused looper to fail. It was also the last step in the log.
In future, I will be documenting errors in detail. Apologies for a newbie mistake!

**Comment by vreuter** [comment]
Not a big deal @ninamw . It still helps to be aware of it, so thanks for calling this out.

**Comment by nsheff** [comment]
I believe this may be a manifestation of #41 -- I believe the fix is already on `features_0.5` branch and just not in the master branch yet.

**Comment by nsheff** [comment]
@ninamw I believe the latest release (v0.5) solve Ninad's issue, so I'll close this, but please correct if it arises again.
