### ISSUE TITLE
Adjust `AttributeDict` serialization and text representation

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#50]
Point 3 in https://github.com/epigen/looper/issues/40#issue-208183000

**Comment by nsheff** [comment]
I'd like to make the current branch an official 0.5 pre-release, but first want to make sure all issues are incorporated. Is this still pending and targeted for 0.5?

**Comment by vreuter** [comment]
Addressed with removal of `Logger` instance from instances of `AttributeDict` and its child classes, along with test coverage in https://github.com/epigen/looper/pull/70
