### ISSUE TITLE
Standardizing Exception levels

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#51]
From @vreuter noted in #40
>  Processing doesn't stop at many of the errors because there are several places in this code that have very generic Exception types in their catch/except clause with no re-raising. I don't like that and agree that processing should stop, but I left those as-was in many places because I thought perhaps that was intended behavior?

We should go through exception types and make sure the levels match what we would expect. This issue is just to capture this thought which we will do at some point.

**Comment by nsheff** [comment]
Duplicate of #52

**Comment by vreuter** [comment]
Lol real-time issue creation collision

**Comment by nsheff** [comment]
I won, apparently :smile:

**Comment by vreuter** [comment]
Haha, indeed! :octocat: ⏲ ⚖️
