### ISSUE TITLE
Proposal: merge pipeline interface and protocol mapping into one config file

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#55]
To prevent relying on a hard-coded folder structure, let's merge protocol mappings into a component of pipeline_interface.yaml and move those up one level, and then make the paths to pipelines in protocol_mappings relative to this file; 

this eliminates the hard-coded paths of 'config' and 'pipelines' subfolders we are currently employing.

**Comment by nsheff** [comment]
Have been thinking about this more and I think it's a really good idea; greatly simplifies the process of connecting a pipeline to looper as it now would be just a single file. we could maintain backwards compatibility for a little while by introducing a new config element: 
```
metadata:
  pipeline_interfaces:
```
`pipeline_interfaces` points directly at interface files (replaces pipelines_dir)

**Comment by vreuter** [comment]
So we keep existing metadata attribute requirements in place *unless* we find a `pipeline_interfaces` element, in which case we use whatever data is contained within the file it points to? That sounds good to me!

**Comment by vreuter** [comment]
I think that this is also a nicety on the development side; labeling accordingly...

**Comment by nsheff** [comment]
@afrendeiro would appreciate your feedback here.

**Comment by vreuter** [comment]
Was addressed with https://github.com/epigen/looper/pull/103
