### ISSUE TITLE
Have more complete real-data tests in place so that devs don't break things

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#58]
This has come up in several spots now. People unfamiliar with the code should feel more free to make changes without having to bite nails and pull hair worrying that changes will break specific real-use cases. Motivated by reappearance of https://github.com/epigen/looper/issues/5

**Comment by nsheff** [comment]
No questions here; microtest was an effort in the direction but it's tied to specific pipelines and not generic.

**Comment by nsheff** [comment]
But actually it might be helpful for you; try to get this to work: https://github.com/epigen/microtest

**Comment by vreuter** [comment]
Something that's already in place that would be useful for this is the submissions files that are created during, say, a dry run.
