### ISSUE TITLE
Proposal: use 'protocol' instead of 'library'

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#59]
I propose we allow `protocol` for `library` -- keep both but allow protocol because sometimes a sample may not be an NGS sample, and `library` is restrictive.

SO, I propose:
Switch to using `protocol` as the keyword column name. If `library` is defined, then stick that into the `protocol` field for backward compatibility.

**Comment by vreuter** [comment]
I like the change, but I'd favor disallowing `library`. If we definitely want to keep it, can we have something like a `DeprecationWarning` if `library` is encountered, for all 0.x versions? Then truly deprecate it and make it an error in >= 1.x versions?

**Comment by nsheff** [comment]
@afrendeiro any objections?

**Comment by vreuter** [comment]
https://github.com/epigen/looper/pull/98 moves in this direction. It maintains "library" as the actual attribute/column name, but some variable name changes accord with this idea. I think the main additional changes needed to complete this transition would be to the docs, the value of the `_protocol` variable used locally in `looper.looper.run`, and to a few spots in `scripts/make_trackhubs.py`

**Comment by vreuter** [comment]
This is finished as of #162 ; I've used `protocol` as an alternative with success.
