### ISSUE TITLE
Either make Sample implement Sequence or Mapping, or remove __getitem__

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#63]
It's strange to be able to use getitem/indexing syntax on an object that's neither a sequence nor a mapping. This looks possible with `Sample`. It may be nice to either force attribute-style access, or to complete an implementation of `Sequence` or `Mapping`.

**Comment by afrendeiro** [comment]
I think this comes historically from Sample being created from a pandas.Series, which behaves like that.
In fact, originally Sample was inheriting from pandas.Series but ultimately I dropped it so that our objects would not break with potential differences in pandas versions.

**Comment by vreuter** [comment]
Ah OK, maybe we should keep it as-is then? If that's what you & @nsheff are used to, along with other users/devs, maybe that's better; it's entirely possible that the seeming oddity of some things to me just stems from being new to the project.

**Comment by nsheff** [comment]
Well, Sample extends AttributeDict, right? so, it's a dict...

**Comment by vreuter** [comment]
No, it extends `object`

**Comment by nsheff** [comment]
indeed. I think Sample should extend AttributeDict.

**Comment by afrendeiro** [comment]
I actually have no strong preference, was just providing some historical context :)

**Comment by vreuter** [comment]
Addressed with `Sample` implementing `AttributeDict` in https://github.com/epigen/looper/commit/51a4b1bd0654e3e87c8f3af7a243e29c570af243
