### ISSUE TITLE
Allow Project and PipelineInterface constructors to handle Iterable of text data or delimited text data

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#64]
Arose from discussion with @nsheff about providing easy interactive test construction modes. We could version control various mock project subdirectories within tests to provide construction and execution scenarios, and perhaps having one or two such directories would provide valuable example(s) to devs/users about how to set up such directories, a sort of tangible example to complement the project documentation. 

Beyond one or two such examples, though, this can become unwieldy. As such, it's simpler to place the lines within `conftest` or another tests helper module and write out that text data to tempfiles, which can be easily cleaned up after each test/class/etc. This complicates construction of instances of the core models for interactive use during test case authorship, though. One way to continue to provide that option is to have a test helper function that could be imported and invoked from an iPython session. Another is to import the actual data variable (e.g., a collection of lines), and pass that directly to the desired object constructor. In fact, the proposed helper function would basically just wrap this operation.

Nonetheless, it would be ideal to allow the core objects' constructors (i.e., those of `Project` and `PipelineInterface` to handle raw delimited text or an `Iterable` of text data). It's plausible that users of the `models` abstractions, particularly outside of the scope of `looper` may have use cases in which they would prefer not to have to write a stream of data out to a file in order to construct a `Project` or `PipelineInterface` instance.

**Comment by afrendeiro** [comment]
Similar to #75, both pandas.read_csv and yaml.load can accept streams of data as input.

Maybe there is a smart way of handling simultaneously strings pointing to data (paths or URLs) and strings or collections of them as actual data to be read by those functions.

**Comment by vreuter** [comment]
Yes, that's definitely doable and what I'd like to allow. I also plan to allow any iterable of text data, though, e.g. a list of lines. I think that read_csv and the yaml loader still both want an object with a read() method if not given a path. I'd like to permit the separation of opening/closing buffers from the constructors, which is straightforward once the constructors can accept just a collection of lines in addition to a file-like.

**Comment by vreuter** [comment]
This seems less useful than it initially did.
