### ISSUE TITLE
Attributes & methods in class docstrings

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#69]
Some of our classes are large in terms of number of methods offered and attributes attached. It's nice to be able to see within the class docstring--both within the code, and then automatically on the web-hosted docs--which methods and attributes are offered on which classes. This is particularly helpful when attributes are defined and assigned outside of the constructor.

I think that sphinx offers some automation capability in this regard. Maybe some of the classes will shrink a bit over time if they're split up a bit, but it seems slightly more like that they could expand. Regardless, this enriched sort of documentation would help devs and users alike.

**Comment by nsheff** [comment]
yes; we have done this for pypiper, see: http://pypiper.readthedocs.io/en/latest/api.html

**Comment by vreuter** [comment]
beautiful! :gem:

**Comment by nsheff** [comment]
@vreuter I realized this documents methods; Can you describe/point how to document attributes as well?

**Comment by nsheff** [comment]
This is done here: http://looper.readthedocs.io/en/latest/api.html
Was there anything else you were looking for or is that it?

**Comment by nsheff** [comment]
the API isn't rendering correctly anymore.
I think it has something to do with this:
```
/home/docs/checkouts/readthedocs.org/user_builds/looper/checkouts/latest/doc/source/api.rst:6: WARNING: autodoc: failed to import module u'looper.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/looper/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/looper/checkouts/latest/looper/models.py", line 66, in <module>
    import pandas as _pd
ImportError: No module named pandas
```

did something get messed up in requirements?

**Comment by nsheff** [comment]
BTW, it renders correctly when I build docs on my computer, but readthedocs is broken now (that's what I meant with the above comment).

**Comment by vreuter** [comment]
Hmm does readthedocs rely on requirements.txt in the repo root maybe? Ours is named slightly differently and nested within a requirements folder.

**Comment by vreuter** [comment]
I thought we'd had it that way for a while but maybe it's newer than I thought

**Comment by nsheff** [comment]
I haven't checked those API docs in awhile, could be it.

**Comment by nsheff** [comment]
@vreuter this problem appears to persist -- I am not sure why but the API in readthedocs got broken somewhere along with our updates to the requirements I think. since you have a better feel for the requirements changes can you look into figuring out how to get the API to display again? I think it will be easier for you than for me.

http://looper.readthedocs.io/en/latest/api.html

the errors show up for example in the  7th box on this page:

http://readthedocs.org/projects/looper/builds/5685575/

**Comment by vreuter** [comment]
Yep will do

**Comment by vreuter** [comment]
OK, I *think* it worked this time...it appears to have, anyway. Can you take a look?

**Comment by nsheff** [comment]
you're right. it worked. what fixed it?

**Comment by vreuter** [comment]
I changed the settings for the build to go into a virtualenv and specified the reqs file path relative to the repo root. It sounded like A is required for B; I think it's B that had the effect, as we hypothesized (we're onto you, readthedocs!)
