### ISSUE TITLE
URLs for sample sheets

### ISSUE THREAD

**Issue by johanneskoester** [epigen/looper#75]
It would be nice if sample sheets can be defined as URLs. This way, it would be possible to share them via Dropbox and Google docs, and collaboratively edit them.

**Comment by nsheff** [comment]
Been thinking about this. The argument against doing this is that then someone else could change your stuff and next time you run it, it gives something different... personally I think this would bother me; I prefer the method of including sample sheets in a git repository and then cloning that repository to run a project -- so collaborative editing is still possible, it just happens through git so I can pull changes when I want to.

However, maybe for a big project that updates frequently or something, or to share with people who don't want to use git (gasp!), this could work. So I don't see any reason not to make it an option, if people think it's useful. Shouldn't be too hard. Thoughts @afrendeiro ?

**Comment by afrendeiro** [comment]
I thought this was by default allowed and already implemented because the pandas function that reads the csv can receive an URL as input:
```
?pandas.read_csv()

Parameters
----------
filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath
or any object with a read() method (such as a file handle or StringIO).
The string could be a URL. Valid URL schemes include http, ftp,
s3, and file. For file URLs, a host is expected. For instance, a local
file could be file://localhost/path/to/table.csv
```
Example - create a sample sheet directly from a URL:
```python
from looper.models import SampleSheet, Project
ss = SampleSheet("https://raw.githubusercontent.com/epigen/microtest/master/config/microtest_annotation.csv")
ss.samples
Out: []
ss.make_samples()
ss.samples
Out: [Sample 'Amplicon_human',
 ATAC-seq sample 'ATAC-seq_human_PE',
 ATAC-seq sample 'ATAC-seq_human_SE',
 ...
 Sample 'SMART-seq_human_truseq_SE',
 Sample 'WGBS_human_1',
 Sample 'WGBS_human_2']
```
However, when an URL is given as sample_annotation in the config file this fails. To investigate, I decoupled Project creation and SampleSheet initialization and saw that the built path to the annotation sheet had been altered (was made relative to the config file).

The issue is therefore with the expectation (or requirement) that the given `sample_annotation` value in the config is relative to the config file itself (see this section https://github.com/epigen/looper/blob/master/looper/models.py#L484).
We should instead see if the given values are absolute (or a link) and if not treat them as relative.

**Comment by nsheff** [comment]
Yes, I thought it used to allow absolute paths and only consider relative if it wasn't absolute... but yes, that's the way it should be.

I might have messed it up when I was merging metadata and paths sections. Or it is possible that the python `abspath` lookup doesn't recognize a URL as an absolute path...

**Comment by vreuter** [comment]
Are you talking about `os.path.isabs`, or something else? The `os` one shouldn't recognize a URL as absolute.

**Comment by nsheff** [comment]
Yeah I meant `os.path.isabs` -- the culprit line is here, then:

https://github.com/epigen/looper/blob/636d579559c5e7809ab943f846b4ce3dff3999e9/looper/models.py#L532

It will make a URL relative I think.

**Comment by vreuter** [comment]
Yep that'd do it. OK, so we want to just add/modify a conditional to permit URL-likes...there's maybe something already in a urllib module, or perhaps a related module? If not, we could write a small helper function to make the determination. What protocols would we want to recognize? Just http/https?

**Comment by vreuter** [comment]
Could maybe also just check for "://" as pattern in path, since it'd be...odd...to have that part of a real directory name. =D

**Comment by nsheff** [comment]
Here's how i've done it before:

https://github.com/databio/refgenie/blob/7552ed9a4ccf8be0c48f766a508064d6b128e81f/src/refgenie.py#L8

**Comment by nsheff** [comment]
dev branch works now on URLs in project config files, in my test case.
