### ISSUE TITLE
Validation of project config sections

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#77]
I ran into a bit of confusion due to a letter substitution in derived_columns. It could be helpful to make warnings louder and/or more immediate for cases in which an unknown project section name is supplied.

**Comment by nsheff** [comment]
but we want to allow customized project sections without issue.

**Comment by vreuter** [comment]
Yeah this makes sense in the context of the models generalization goal, so it could probably be closed. I think it's still good to validate the sections that we know about/require, especially before actually submitting anything but that spirit differs quite a bit from this and more similar to https://github.com/epigen/looper/issues/23

**Comment by nsheff** [comment]
the problem is we want:
1. almost every section should be optional
2. any custom section should be tolerated without issue

this makes it almost impossible to test for and catch errors like the above...

**Comment by vreuter** [comment]
Right, so I think that this one can be closed, right? Or are you thinking there's something that we should do related to this one?
