### ISSUE TITLE
Constructor arg type hints

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#78]
The docs nicely display type and description information for function parameters and other tags, but it looks like that's lost for classes that couple parameters information with `__init__` rather than with the class declaration header itself. For instance, `SampleSheet` pairs the parameters and type information in the class docstring and gets the nice docs benefit, but many other classes don't. 

My pattern had been to define these in the `__init__` and reserve the class docstring space for a longer description and example(s). If there's a docs build/render strategy that would accommodate both, I'd like to use that, but if not I will switch to the way used as in `SampleSheet`. In that case, I will also convert existing classes that I've written to the `SampleSheet` way so that we get the constructor type info in the docs.

**Comment by vreuter** [comment]
Consider https://github.com/epigen/looper/issues/73

**Comment by vreuter** [comment]
http://www.sphinx-doc.org/en/stable/ext/autodoc.html
https://bitbucket.org/etienned/sphinx-autopackage-script/src
http://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method

**Comment by nsheff** [comment]
@afrendeiro  do you have a comment on this?

**Comment by vreuter** [comment]
While it'd be nice to not have style mixture, it's no big deal
