### ISSUE TITLE
Only write out AttributeDict behavior metadata if different than default

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#79]
Behavior metadata is written when an AttributeDict (or subclass) is dumped to disk: https://github.com/epigen/looper/issues/50
This is needed to preserve behavior if the object in question is restored, but this may be rare? It'd be nice to add control over whether this information is written to disk, as it's tedious to look through job submission YAML files that have these data for every K-V pair.

**Comment by nsheff** [comment]
Can you provide an example of what this looks like here, in the dumped yaml?
Can it be made to leave empty (print nothing) if no such metadata exists (default), but only include if the metadata is present?

**Comment by vreuter** [comment]
Yeah I saw it in a now-deleted (and unavailable, anyhow) ratbrain logfile on Rivanna, but I'll generate something similar.

**Comment by vreuter** [comment]
TXT i/o YAML in extension only, to make GitHub happy

[testsample.txt](https://github.com/epigen/looper/files/842626/testsample.txt)

**Comment by vreuter** [comment]
I don't think there's a clean way to disambiguate between someone providing one/both default values vs. not providing them, but it could be made to only write that out if the values are different than the defaults, because then we would know that they had been set. In fact, I guess there'd really be no advantage to writing out the default values, even if we could tell whether they'd been set that way or just adopted automatically. Either way, the same behavior would be recovered if that YAML data was used to reconstitute the object, whether or not the default values are present. So anyway, yes I think that can (and should!) be done. I think jjust making that the behavior is better than providing an parameter that almost no one would care about and that would complicate the code logic. Plus we get a sort of for-free smaller YAML out of it, omitting the default data.

**Comment by nsheff** [comment]
Yes, I think this is a good solution, unless @afrendeiro has any thoughts.

**Comment by afrendeiro** [comment]
Yes, I agree the yaml has a lot of stuff that is often not that relevant since it was conceived primarily as a way to serialize the Sample object. Since often only the more sample-specific attributes (i.e. in the root level of the yaml) are used, this could be simplified.

However, I don't understand what you're referring to as *defaults* for a sample: are these stuff under "prj" like "looperenv" and so on?

I personally use these yamls to reconstitute the sample objects inside a pipeline run, but I actually use mostly only those sample-specific attributes in the root level, so it would be nice to keep having them.

**Comment by vreuter** [comment]
Sorry about the ambiguity @afrendeiro . By defaults I meant specifically for two new fields, but just on `AttributeDict` and not on `Sample`, that pertain to dealing with nulls values and for requesting nonexistent attributes, both of which are `False` by default. The writing/reading of attributes on `Sample` should be unaffected.

1 -- "_force_nulls" dictates how to handle an attempt to add a `None` for a key.
2 -- "_attribute_identity" allows request for a nonexistent attribute to return the requested name itself. 

For example:

`ad = AttributeDict(_force_nulls=True, _attribute_identity=True)`

would allow `ad` to behave like:
```
>>> ad.bowtie2
"bowtie2"
>>> 
>>> ad.picard = "picard.jar"
>>> ad.picard
"picard.jar"
>>> ad.picard = None
>>> ad.picard
>>> 
```

I haven't made use of these yet, but @nsheff mentioned that these could be useful and they've been added now, but they're off/False if unspecified.

**Comment by afrendeiro** [comment]
Ah, thanks for clarifying. I wasn't aware of those latest defaults.
In this case I don't see any problem in omitting them from Sample serialization to yaml.
