### ISSUE TITLE
Prompt for missing required attribute(s)

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#81]
Rather than stopping execution with an exception, prompt user for value(s) if attribute(s) are missing from a project/subproject configuration.

**Comment by nsheff** [comment]
I'm not sure we want to go down this route... we don't want to enable fixing these things on-the-fly, but enforce users to do it right; otherwise they'll get a prompt every time (run, check, etc) and with other software, too (R, whatever).

**Comment by vreuter** [comment]
Yeah misunderstood what you meant the other day & opened this too quickly; I agree.
