### ISSUE TITLE
Manual resources

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#86]
Resource request is made as a selection from among defined bundles in a looperenv config, with inference coming from file size. This is a nice feature but some clusters may be configured to reject submission of jobs with large resource requests for a given partition. In this case, it could useful to provide a key-value in the project config directly specifying which of the resource bundles to use.

**Comment by nsheff** [comment]
not quite true; resource bundles are defined in the pipeline interface, not looperenv. partition/queue is defined in looperenv and is configurable manually already, either on the command line or in the project config. this just needs to be optimized for a given looperenv in that environment...

**Comment by vreuter** [comment]
Yep good call, I see it now in the project config portion of the docs. Docs also mention `--compute` as a CLI option. Could this be added in the help text? Also, what do you mean by the environment-specific optimization, the slot-like selection mechanism based on the calculation from file size?

**Comment by nsheff** [comment]
it's there under `looper run --help` -- no, just that you have to configure your looperenv to fit your compute environment, as you would expect.

**Comment by vreuter** [comment]
This was really a two-parter:
1. Allow definition and use of resource bundles different from those defined by a pipeline author. The developer has some knowledge of resource needs, but a user may desire additional control/customization.
2. Allow *limited* specification of non-resource compute settings (partition + submission command & template) in the project configuration file.

https://github.com/epigen/looper/commit/460ebe9f1a1b1dd76478dd4d3b2eebd9627eb957 solves the first of these with its enhancement of pipeline interface flexibility. The second is now https://github.com/epigen/looper/issues/114
