### ISSUE TITLE
increase verbosity of required inputs not found

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#88]
Small thing: if a pipeline is not submitted because input files are not found, right now looper says:
```
 Not submitted: Required input files not found
```
I think in this case it should state specifically which files are missing. It does in `--debug` mode but this might be worth displaying to the user.

**Comment by vreuter** [comment]
:+1: Is this in dry run, real run, or both?

**Comment by nsheff** [comment]
at least real; probably both.
