### ISSUE TITLE
Make project definition more generic

### ISSUE THREAD

**Issue by johanneskoester** [epigen/looper#93]
Hi guys,
I have played with the API and must say I like it. Everything is clean and intuitive.
I think it should be generalized a bit though.

* Why does the sample sheet require a library column? This term may not apply in my experiment (or I don't care because it is all the same) and it seems a bit artificial to require that.
* Why the requirement of a data source/file column?
* The metadata section should not need the two keys output_dir and pipelines_dir, because they are not needed as well in every setting (e.g. when not using looper).
* I have a problem with the column `run` because it is ambiguous with what people sometimes use to call a sequencing run. Instead one could call it `blacklist`.

I really would like to see the sample sheet implementation together with these data source patterns outside of looper (without the looper specific syntax).

* [x] move `library` column requirement to looper. See #59 
* [x] move data source column requirement to looper
* [x] move `output_dir` and `pipelines_dir` requirements to looper
* [x] rename `run` to `toggle`

**Comment by vreuter** [comment]
Here we have some specific questions and ideas related to https://github.com/epigen/looper/issues/74

**Comment by vreuter** [comment]
Thanks @johanneskoester for trying this out and providing some feedback and ideas.

**Comment by nsheff** [comment]
Agreed. Essentially we should move all these checks into looper and out of models.

* [ ] move `library` column requirement to looper. See #59 
* [ ] move data source column requirement to looper
* [ ] move `output_dir` and `pipelines_dir` requirements to looper

For the `run` column... I don't like `blacklist` because it, too, could be a common parameter name to a pipeline, messing things up. What about `toggle` or `runbool` instead?

Let's do all these things for milestone `0.6`

For separation, we just refer back to #74; continue discussion in that thread.

**Comment by johanneskoester** [comment]
I like toggle.

**Comment by afrendeiro** [comment]
Why not exactly what it means: `submit_job`?

**Comment by johanneskoester** [comment]
Because this is not what it necessarily means in any context. For example, there could be only one job aggregating over all samples. In Snakemake, such sample metadata can be used in an arbitrary way.

**Comment by afrendeiro** [comment]
Yes, I guess I should have said: "why not exactly what it means *for looper*".
In that case I guess `toggle` would accommodate both.

**Comment by vreuter** [comment]
https://github.com/epigen/looper/pull/98/files attempts to address 1-3. @johanneskoester what was the requirement on `library` that you encountered with `SampleSheet`? There's a check within `looper run` regarding that attribute, but I think that it should be possible to create and use a `Sample` without it, but I may be missing a use case. Did you encounter a check when using a `Sample` interactively/in isolation, or during a `looper run`?

**Comment by johanneskoester** [comment]
@vreuter I did not check that in my test, I just saw it in the documentation. So if there is no check when using `Sample` directly, I guess it is sufficient to adapt the documentation.

**Comment by vreuter** [comment]
Got it, thanks @johanneskoester . https://github.com/epigen/looper/pull/98 has been updated to `toggle` and some docs clarification.

**Comment by nsheff** [comment]
@vreuter Just wanted to follow-up on this -- is this issue solved?

Did our #98 merge address all of the 4 tasks above? if so I guess we should check this off and close the issue. For example on the `data_source` thing -- we leave the population of the attribute in models but did the requirement move to `looper`?

**Comment by vreuter** [comment]
Yep
